### ISSUE TITLE
Missing Includes

### ISSUE THREAD

**Issue by JeremyJStarcher** [hhornbacher/node-scad-parser#8]
Not even at the stage of trying to run things yet, but I did notice you've got some missing `scad` includes:

```
include <tools.scad>;
use <junctions.scad>;
include <../helper.scad>;
```

You've also got at least one file hard-coded into your code:

`testRender: () => parser.render(null, '/home/harry/Dokumente/Development/Private/3D/thermostirrer/coil-holder.scad').then(out => console.log(out))`

**Comment by hhornbacher** [comment]
Hi and thanks for this information,
the missing includes are just made up and do not exists. (For testing if the parser parses the statements correctly).
The coil-holder.scad file I added to the examples directory and fixed the code regardingly.
